export const CREATE_CONTACT_START = "CREATE_CONTACT_START";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";

export const SET_FORM_DATA = "SET_FORM_DATA";
